### ISSUE TITLE
Hata alıyorum üstad yardım edermisin?

### ISSUE THREAD

**Issue by cem-canpolat** [furkankadioglu/efatura#90]
Üstad merhaba,
Öncelikle emeğine sağlık, kendi işimiz için e-fatura entegrasyanona ihtiyacım vardı, ancak e-arşiv dökümanlarından hiç bir şey anlamamıştım, neyse ki senin apin çıktı karşıma ve çok sevindim teşekkürler, ancak bir hata alıyorum acaba yardımcı olabilir misin zamanın varsa?

Test hesabına sorunsuz bağlanıyorum ancak kendi hesabıma bağlanırken aşağıdaki hatayı alıyorum.
try catch arasında yazdığımda kodlarını, ekrana bu çıktıyı alıyorum.

cURL error 35: error:0A000152:SSL routines::unsafe legacy renegotiation disabled (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://earsivportal.efatura.gov.tr/earsiv-services/assos-login

try catch dışında da bu hatayı alıyorum

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 35: error:0A000152:SSL routines::unsafe legacy renegotiation disabled (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
#0 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke()
#11 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer()
#12 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync()
#13 /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\Client->request()
#14 /var/www/html/Trendyol/Helper/Invoice2/vendor/furkankadioglu/efatura/src/InvoiceManager.php(267): GuzzleHttp\Client->__call()
#15 /var/www/html/Trendyol/Helper/Invoice2/vendor/furkankadioglu/efatura/src/InvoiceManager.php(290): furkankadioglu\eFatura\InvoiceManager->sendRequestAndGetBody()
#16 /var/www/html/Trendyol/Helper/Invoice2/vendor/furkankadioglu/efatura/src/InvoiceManager.php(225): furkankadioglu\eFatura\InvoiceManager->getTokenFromApi()
#17 /var/www/html/Trendyol/Invoiced/invoice.php(7): furkankadioglu\eFatura\InvoiceManager->connect()
#18 /var/www/html/Trendyol/index.php(48): include('...')
#19 {main}
  thrown in /var/www/html/Trendyol/Helper/Invoice2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200

**Comment by truncgil** [comment]
cURL sürümünü ve konfigürasyonları kontrol ediniz. Guzzle hatası da cURL kaynaklı.
